---
baseurl: "/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "ZB的博客"
theme: "beautifulhugo"
metaDataFormat: "yaml"
algolia:
 index: "prod_k8sz"
 key: "8ca8105cef83b57d5cf1122941280707"
 appID: "OGF3JK7MAT"
---
